name: Jio Play IPTV EPG Daily Workflow

on:
  workflow_dispatch:
  schedule:
    - cron: "00 21  * * *"
  push:
    branches: [ main ]

jobs:

  epg:
    name: Jio Play IPTV EPG Setup
    runs-on: ubuntu-latest
    steps:

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Get EPG Data
      run: chmod +x bin/epg_linux_x64.json && ./bin/epg_linux_x64.json
    
    - name: Update release
      env:
          GITHUB_TOKEN: ${{ secrets.GIT_TOKEN }}
      run: |
        hub release edit -a epg.xml -a epg.xml.gz -m "EPG has been updated." latest
  
