name: EPG Service

on:
  workflow_dispatch:
  schedule:
    - cron: "30 3 * * *" # every day at 3:30am UTC (9:00am IST)
  push:
    branches: [ main ]

jobs:

  epg:
    name: EPG Setup
    runs-on: ubuntu-latest
    steps:

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Download binary
      env:
        RELEASE_TOKEN: ${{ secrets.RELEASE_TOKEN }}
      run: |
        curl -u '1:${{ env.RELEASE_TOKEN }}' -H 'Accept: application/octet-stream' --output "epg_linux_amd64" -L $(curl -u '1:${{ env.RELEASE_TOKEN }}' https://api.github.com/repos/iMro0t/epg/releases/latest -s | jq -r '.assets[] | select(.name=="epg_linux_amd64") | .url')
        chmod +x epg_linux_amd64

    - name: Get EPG Data
      run: ./epg_linux_amd64 -source jiotv
    
    - name: Update release
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        hub release edit -a epg.xml -a epg.xml.gz -m "" latest
        
